# Generated by Django 6.0.2 on 2026-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimber_app', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
    ]
