# Generated by Django 6.0.2 on 2026-03-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimber_app', '0003_alter_customuser_age_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
    ]
