# Generated by Django 6.0.3 on 2026-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimber_app', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
